[tool.pyright]
include = ["src/code"]
exclude = []
typeCheckingMode = "strict"

reportMissingParameterType = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"

pythonVersion = "3.12"
pythonPlatform = "Linux"

[tool.isort]
line_length = 88
profile = "google"
src_paths = ["src/code"]
forced_separate = ["typing"]
